const importedData = [
  {
    "name": "三谷将太",
    "url": "https://keirin.jp/pc/racerprofile?snum=014252",
    "kyuhan": "Ｓ級１班",
    "kyuhanDate": "2023/07/01",
    "kyuhanHist": "Ｓ級２班",
    "kyuhanHistDate": "2023/01/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ｓ級１班",
    "totalWins": 227,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 227,
    "failed": false
  },
  {
    "name": "三谷竜生",
    "url": "https://keirin.jp/pc/racerprofile?snum=014873",
    "kyuhan": "Ｓ級１班",
    "kyuhanDate": "2022/01/01",
    "kyuhanHist": "Ｓ級２班",
    "kyuhanHistDate": "2021/07/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ｓ級１班",
    "totalWins": 330,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 330,
    "failed": false
  },
  {
    "name": "中井太祐",
    "url": "https://keirin.jp/pc/racerprofile?snum=014605",
    "kyuhan": "Ｓ級１班",
    "kyuhanDate": "2023/01/01",
    "kyuhanHist": "Ｓ級２班",
    "kyuhanHistDate": "2022/07/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ｓ級１班",
    "totalWins": 344,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 344,
    "failed": false
  },
  {
    "name": "中井俊亮",
    "url": "https://keirin.jp/pc/racerprofile?snum=014945",
    "kyuhan": "Ｓ級２班",
    "kyuhanDate": "2026/07/01",
    "kyuhanHist": "Ｓ級１班",
    "kyuhanHistDate": "2026/01/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ｓ級２班",
    "totalWins": 280,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 280,
    "failed": false
  },
  {
    "name": "山本伸一",
    "url": "https://keirin.jp/pc/racerprofile?snum=014886",
    "kyuhan": "Ｓ級２班",
    "kyuhanDate": "2026/07/01",
    "kyuhanHist": "Ｓ級１班",
    "kyuhanHistDate": "2024/01/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ｓ級２班",
    "totalWins": 266,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 266,
    "failed": false
  },
  {
    "name": "佐藤成人",
    "url": "https://keirin.jp/pc/racerprofile?snum=012688",
    "kyuhan": "Ｓ級２班",
    "kyuhanDate": "2026/07/01",
    "kyuhanHist": "Ａ級１班",
    "kyuhanHistDate": "2026/01/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ｓ級２班",
    "totalWins": 334,
    "currentRace": [
      "大宮Ｆ１ 10/06\nＳ級予選/9R（7着）",
      "大宮Ｆ１ 10/07\nＳ級一般/8R（-着）",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 334,
    "failed": false
  },
  {
    "name": "伊代野貴照",
    "url": "https://keirin.jp/pc/racerprofile?snum=014878",
    "kyuhan": "Ｓ級２班",
    "kyuhanDate": "2020/01/01",
    "kyuhanHist": "Ｓ級１班",
    "kyuhanHistDate": "2019/07/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ｓ級２班",
    "totalWins": 217,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 217,
    "failed": false
  },
  {
    "name": "栗山俊介",
    "url": "https://keirin.jp/pc/racerprofile?snum=014944",
    "kyuhan": "Ｓ級２班",
    "kyuhanDate": "2024/01/01",
    "kyuhanHist": "Ａ級１班",
    "kyuhanHistDate": "2023/07/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ｓ級２班",
    "totalWins": 223,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 223,
    "failed": false
  },
  {
    "name": "元砂勇雪",
    "url": "https://keirin.jp/pc/racerprofile?snum=014946",
    "kyuhan": "Ｓ級２班",
    "kyuhanDate": "2026/01/01",
    "kyuhanHist": "Ｓ級１班",
    "kyuhanHistDate": "2025/07/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ｓ級２班",
    "totalWins": 206,
    "currentRace": [
      "奈良Ｆ１ 10/05\nＳ級予選/11R（2着）",
      "奈良Ｆ１ 10/06\nＳ級準決勝/11R（4着）",
      "奈良Ｆ１ 10/07\nＳ級特選/8R（-着）",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 206,
    "failed": false
  },
  {
    "name": "田中大我",
    "url": "https://keirin.jp/pc/racerprofile?snum=015363",
    "kyuhan": "Ｓ級２班 特昇",
    "kyuhanDate": "2024/03/01",
    "kyuhanHist": "Ａ級１班",
    "kyuhanHistDate": "2022/07/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ｓ級２班",
    "totalWins": 213,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 213,
    "failed": false
  },
  {
    "name": "辰己豊",
    "url": "https://keirin.jp/pc/racerprofile?snum=013792",
    "kyuhan": "Ａ級１班",
    "kyuhanDate": "2026/07/01",
    "kyuhanHist": "Ａ級２班",
    "kyuhanHistDate": "2026/01/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ａ級１班",
    "totalWins": 263,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 263,
    "failed": false
  },
  {
    "name": "野口正則",
    "url": "https://keirin.jp/pc/racerprofile?snum=015005",
    "kyuhan": "Ａ級１班",
    "kyuhanDate": "2026/07/01",
    "kyuhanHist": "Ｓ級２班",
    "kyuhanHistDate": "2025/07/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ａ級１班",
    "totalWins": 207,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 207,
    "failed": false
  },
  {
    "name": "小笹隼人",
    "url": "https://keirin.jp/pc/racerprofile?snum=015003",
    "kyuhan": "Ａ級１班",
    "kyuhanDate": "2023/07/01",
    "kyuhanHist": "Ｓ級２班",
    "kyuhanHistDate": "2022/01/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ａ級１班",
    "totalWins": 194,
    "currentRace": [
      "奈良Ｆ１ 10/05\nＡ級初特選/5R（2着）",
      "奈良Ｆ１ 10/06\nＡ級準決勝/5R（6着）",
      "奈良Ｆ１ 10/07\nＡ級特選/4R（-着）",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 194,
    "failed": false
  },
  {
    "name": "吉田篤史",
    "url": "https://keirin.jp/pc/racerprofile?snum=015108",
    "kyuhan": "Ａ級２班",
    "kyuhanDate": "2026/01/01",
    "kyuhanHist": "Ａ級１班",
    "kyuhanHistDate": "2024/01/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ａ級２班",
    "totalWins": 167,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 167,
    "failed": false
  },
  {
    "name": "佐山寛明",
    "url": "https://keirin.jp/pc/racerprofile?snum=015269",
    "kyuhan": "Ｓ級２班",
    "kyuhanDate": "2026/01/01",
    "kyuhanHist": "Ａ級１班",
    "kyuhanHistDate": "2024/01/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ｓ級２班",
    "totalWins": 180,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 180,
    "failed": false
  },
  {
    "name": "吉堂将規",
    "url": "https://keirin.jp/pc/racerprofile?snum=015364",
    "kyuhan": "Ａ級１班",
    "kyuhanDate": "2023/07/01",
    "kyuhanHist": "Ｓ級２班",
    "kyuhanHistDate": "2022/07/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ａ級１班",
    "totalWins": 133,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 133,
    "failed": false
  },
  {
    "name": "三谷政史",
    "url": "https://keirin.jp/pc/racerprofile?snum=014310",
    "kyuhan": "Ｓ級２班",
    "kyuhanDate": "2026/07/01",
    "kyuhanHist": "Ａ級１班",
    "kyuhanHistDate": "2026/01/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ｓ級２班",
    "totalWins": 149,
    "currentRace": [
      "大宮Ｆ１ 10/06\nＳ級予選/9R（6着）",
      "大宮Ｆ１ 10/07\nＳ級一般/8R（-着）",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 149,
    "failed": false
  },
  {
    "name": "有馬雄二",
    "url": "https://keirin.jp/pc/racerprofile?snum=014094",
    "kyuhan": "Ａ級２班",
    "kyuhanDate": "2021/07/01",
    "kyuhanHist": "Ａ級３班",
    "kyuhanHistDate": "2020/07/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ａ級２班",
    "totalWins": 207,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 207,
    "failed": false
  },
  {
    "name": "黒川渉",
    "url": "https://keirin.jp/pc/racerprofile?snum=014979",
    "kyuhan": "Ａ級３班",
    "kyuhanDate": "2026/07/01",
    "kyuhanHist": "Ａ級２班",
    "kyuhanHistDate": "2023/01/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ａ級３班",
    "totalWins": 105,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 105,
    "failed": false
  },
  {
    "name": "田村風起",
    "url": "https://keirin.jp/pc/racerprofile?snum=015056",
    "kyuhan": "Ａ級１班",
    "kyuhanDate": "2026/01/01",
    "kyuhanHist": "Ａ級２班",
    "kyuhanHistDate": "2024/07/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ａ級１班",
    "totalWins": 127,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 127,
    "failed": false
  },
  {
    "name": "大崎龍一郎",
    "url": "https://keirin.jp/pc/racerprofile?snum=015105",
    "kyuhan": "Ａ級３班",
    "kyuhanDate": "2020/01/01",
    "kyuhanHist": "Ａ級２班",
    "kyuhanHistDate": "2019/07/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ａ級３班",
    "totalWins": 37,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 37,
    "failed": false
  },
  {
    "name": "西岡利起",
    "url": "https://keirin.jp/pc/racerprofile?snum=015823",
    "kyuhan": "Ｓ級２班",
    "kyuhanDate": "2026/07/01",
    "kyuhanHist": "Ａ級２班",
    "kyuhanHistDate": "2025/07/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ｓ級２班",
    "totalWins": 88,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 88,
    "failed": false
  },
  {
    "name": "伊狩知人",
    "url": "https://keirin.jp/pc/racerprofile?snum=013728",
    "kyuhan": "Ａ級３班",
    "kyuhanDate": "2024/01/01",
    "kyuhanHist": "Ａ級２班",
    "kyuhanHistDate": "2023/07/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ａ級３班",
    "totalWins": 111,
    "currentRace": [
      "静岡Ｆ２ 10/07\nＡ級チ予選/2R（-着）",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 111,
    "failed": false
  },
  {
    "name": "大井啓世",
    "url": "https://keirin.jp/pc/racerprofile?snum=011519",
    "kyuhan": "登録番号",
    "kyuhanDate": "",
    "kyuhanHist": "",
    "kyuhanHistDate": "",
    "nextKyuhan": "",
    "profileCurrentRank": "登録番号",
    "totalWins": 379,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 379,
    "failed": false
  },
  {
    "name": "岡崎和久",
    "url": "https://keirin.jp/pc/racerprofile?snum=013206",
    "kyuhan": "Ａ級３班",
    "kyuhanDate": "2026/07/01",
    "kyuhanHist": "Ａ級２班",
    "kyuhanHistDate": "2026/01/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ａ級３班",
    "totalWins": 292,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 292,
    "failed": false
  },
  {
    "name": "関谷哲平",
    "url": "https://keirin.jp/pc/racerprofile?snum=014251",
    "kyuhan": "Ａ級３班",
    "kyuhanDate": "2023/01/01",
    "kyuhanHist": "Ａ級２班",
    "kyuhanHistDate": "2020/07/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ａ級３班",
    "totalWins": 317,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 317,
    "failed": false
  },
  {
    "name": "肥後公允",
    "url": "https://keirin.jp/pc/racerprofile?snum=014179",
    "kyuhan": "Ａ級３班",
    "kyuhanDate": "2026/01/01",
    "kyuhanHist": "Ａ級１班",
    "kyuhanHistDate": "2025/07/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ａ級３班",
    "totalWins": 218,
    "currentRace": [
      "静岡Ｆ２ 10/07\nＡ級チ予選/5R（-着）",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 218,
    "failed": false
  },
  {
    "name": "元砂海人",
    "url": "https://keirin.jp/pc/racerprofile?snum=015270",
    "kyuhan": "Ａ級３班",
    "kyuhanDate": "2018/05/01",
    "kyuhanHist": "",
    "kyuhanHistDate": "",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ａ級３班",
    "totalWins": 42,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 42,
    "failed": false
  },
  {
    "name": "武田和也",
    "url": "https://keirin.jp/pc/racerprofile?snum=014254",
    "kyuhan": "Ａ級３班",
    "kyuhanDate": "2024/07/01",
    "kyuhanHist": "Ａ級２班",
    "kyuhanHistDate": "2024/01/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ａ級３班",
    "totalWins": 252,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 252,
    "failed": false
  },
  {
    "name": "元砂七夕美",
    "url": "https://keirin.jp/pc/racerprofile?snum=015076",
    "kyuhan": "Ｌ級１班",
    "kyuhanDate": "2017/07/01",
    "kyuhanHist": "Ａ級２班",
    "kyuhanHistDate": "2015/05/01",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ｌ級１班",
    "totalWins": 36,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 36,
    "failed": false
  },
  {
    "name": "馬越裕之",
    "url": "https://keirin.jp/pc/racerprofile?snum=015909",
    "kyuhan": "Ａ級２班 特昇",
    "kyuhanDate": "2026/04/26",
    "kyuhanHist": "Ａ級３班",
    "kyuhanHistDate": "2025/03/09",
    "nextKyuhan": "Ａ級２班",
    "profileCurrentRank": "Ａ級２班",
    "totalWins": 41,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 41,
    "failed": false
  },
  {
    "name": "西田美菜",
    "url": "https://keirin.jp/pc/racerprofile?snum=015948",
    "kyuhan": "Ｌ級１班",
    "kyuhanDate": "2025/03/09",
    "kyuhanHist": "",
    "kyuhanHistDate": "",
    "nextKyuhan": "-",
    "profileCurrentRank": "Ｌ級１班",
    "totalWins": 0,
    "currentRace": [
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ",
      "ｰ"
    ],
    "totalWinsNumeric": 0,
    "failed": false
  }
];